### ISSUE TITLE
Cannot find ETFs on OpenBB that I can find on yahoo finance

### ISSUE THREAD

**Issue by universvm** [OpenBB-finance/OpenBBTerminal#1628]
**Describe the bug**
There are certain ETFs I'm interested in which I can access to through Yahoo Finance which I can't access through OpenBB, for example:

VEUR.AS - https://finance.yahoo.com/quote/veur.as/
VEURX - https://finance.yahoo.com/quote/VEURX?p=VEURX&.tsrc=fin-srch
IWDC.SW - https://finance.yahoo.com/quote/IWDC.SW?p=IWDC.SW&.tsrc=fin-srch

**To Reproduce**
load {NAME_OF_TICKER}

**Screenshots**
<img width="431" alt="Screenshot 2022-04-04 at 10 05 12" src="https://user-images.githubusercontent.com/17524568/161511213-14cd6a57-c29b-4d8f-9650-6bb157f6c6e0.png">

**Desktop (please complete the following information):**

- OS: MacOS Monterey 12.3.1 
- Python version: unsure about which one openBB uses but I default is Python 3.9.12

**Additional context**
Add any other information that you think could be useful for us.

**Comment by colin99d** [comment]
Hey @universvm good find! Unfortunately this is because we get our holding information from StockAnalysis which does not cover the given tickers. For example: https://stockanalysis.com/etf/IWDC.SW/holdings/ gives a 404.
After giving the given ticker you will see that any of our features that depend on StockAnalysis do not work, but any features depending on YahooFinance work perfectly. I am going to go ahead and close this issue since this is the desired behavior.
