### ISSUE TITLE
[Bug] Econometrics Export FileNotFound

### ISSUE THREAD

**Issue by colin99d** [OpenBB-finance/OpenBBTerminal#1667]
**Describe the bug**
Export in Econometrics causes FileNotFoundError.

**To Reproduce**
`load cancer dataset`
`export dataset`

**Screenshots**
<img width="788" alt="Screen Shot 2022-04-10 at 1 47 13 PM" src="https://user-images.githubusercontent.com/72827203/162632444-382f90ab-28cd-434a-90ef-8d7684d61eae.png">

**Desktop (please complete the following information):**

- OS: Mac Monterey
- Python version 3.8

**Comment by JerBouma** [comment]
Does the folder exist at all? Or is this perhaps via the installer application?

I don't understand why this suddenly breaks while it worked when I first designed the menu.

**Comment by colin99d** [comment]
I am not sure if the folder exists and I did not use install using the installer.

**Comment by JerBouma** [comment]
This is via installer version:
![Screenshot 2022-04-11 at 10 18 22](https://user-images.githubusercontent.com/46355364/162694529-10226038-1bb3-
41b6-963e-b2aef5f0b41c.png)

But via the Anaconda version it does indeed crash. Seems like someone removed this folder, will re-add.

**Comment by JerBouma** [comment]
Oh you already fixed this yourself, lol. Just noticed this. I want to include this small remark though:`load in custom data sets` to `load in custom data sets (use -ex for examples)`. I noticed that it wasn't clear there were example datasets available (got the question a couple of times). This should make the menu more accessible for basic testing because these datasets are already cleaned as well.

**Comment by piiq** [comment]
I see the same issue on the latest main. Looks like the exports path (`OPENBB-exports`) is not being set for me and @colin99d. I clearly remember @DidierRLopes adding it so maybe this change was overwritten by some uncontrolled merge

**Comment by colin99d** [comment]
@piiq once my tests work on windows fix will be merged.
