### ISSUE TITLE
[Bug] Stock Search Fails To Search By Industry Because Of Phrases.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1758]
Same problem that was brought up with the Stock Screener and sorting categories with multiple words. 

https://user-images.githubusercontent.com/85772166/166408857-b7b669a6-2eb1-423c-9870-2805f5c845b9.mov

**Comment by PzaThief** [comment]
Just for now I recommend to use double quotes on both side of industry keyword like "search -i "foo bar"?
Because terminal accept multiple parameter using space delimiter, You need to let terminal know that keyword is one parameter of -i(industry) option.
I think we need to improve auto-completion to use double quote when the keyword takes space character

**Comment by deeleeramone** [comment]
This does not work as you describe.

**Comment by PzaThief** [comment]
Sorry for misguided. I fixed it in my branch, so you can pull and use it before merge into main repo.

**Comment by Chavithra** [comment]
Thanks @PzaThief 

Great PR !
