### ISSUE TITLE
[Bug] API openbb.stocks.load not accepting optional arguments

### ISSUE THREAD

**Issue by minhhoang1023** [OpenBB-finance/OpenBBTerminal#2003]
This was reported by users:

openbb.stocks.load("GME") works fine

But openbb.stocks.load("GME", None, None, None, None, None) doesn't work 

Users should be able to pass in their own default values.

![image](https://user-images.githubusercontent.com/40023817/176151958-e2f94d52-606b-457a-aa4e-d7c9ca24f53b.png)

**Comment by northern-64bit** [comment]
openbb.stocks.load("GME", None, None, None, None, None) doesn't work since the None overwrites the default values so the function gets unfunctional input. Proof of this is that openbb.stocks.load("GME", 1, 1, 1, 1, 1) generates the same error.

openbb.stocks.load accepts optional arguments, see picture:
![image](https://user-images.githubusercontent.com/75195383/176190960-a8919a3f-0603-42b8-843f-edba0fc98733.png)

So this shouldn't be an issue at all

**Comment by minhhoang1023** [comment]
So it only accepts "some optional" arguments, but not all. Can we have it such that all optional arguments can be set and not generating that type of error?

**Comment by northern-64bit** [comment]
Here is every argument possible set and it works:
![image](https://user-images.githubusercontent.com/75195383/176199718-357bd9ec-a63d-47be-8b15-67ec5077f210.png)

**Comment by colin99d** [comment]
I am going to close this issue. The arguments do not accept None because they need default values.
