### ISSUE TITLE
 [Bug] Exit fails because of the way the we are trying to get parameters form controller below

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#2053]
<img width="971" alt="Screenshot 2022-07-06 at 15 36 17" src="https://user-images.githubusercontent.com/25267873/177578906-7c2b3608-7a51-4382-bd70-3b515ba3da16.png">

@colin99d you implemented this solution, could you have a look at what's going on? The issue is in that area and has to do on how you get parameters from controllers that have been previously loaded

**Comment by colin99d** [comment]
So what exactly is the issue here?

**Comment by jmaslek** [comment]
> So what exactly is the issue here?

From `/portfolio/po/`, if you access the `/params/` sub(sub)menu and change things, we want those parameters brought back to `po`.  It seems that when we either do `exit` or `reset` from the params menu, the `/portfolio/po/params` class doesn't save.

@DidierRLopes does the functionality work outside of using `reset` or `exit`?  Because this error doesn't pop up if you do `q`

**Comment by colin99d** [comment]
I am confused on what the error is with `exit`. Doesnt this exit the entire terminal?
