### ISSUE TITLE
[Bug] Options/Chains - yFinance Source creates an error where --source Tradier does not. Error: float division by zero. Error: 'list' object has no attribute 'fillna'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2216]
To reproduce, load AMZN, enter options, select the expiration for 2022-12-16, enter `chains`

<img width="1051" alt="Screen Shot 2022-07-31 at 12 32 53 PM" src="https://user-images.githubusercontent.com/85772166/182042258-72526761-2d52-441c-8762-34aff9e9b6ee.png">

```
 /stocks/options/ $ chains
Error: float division by zero

Error: 'list' object has no attribute 'fillna'
```
A different expiration date does not produce the error, but Tradier as a source has no problems with it.

<img width="1072" alt="Screen Shot 2022-07-31 at 12 33 59 PM" src="https://user-images.githubusercontent.com/85772166/182042280-780459d2-4c37-49ab-8023-827836baf96a.png">

A couple of notes on this command as well: 

- Why does the function not respect `load [ticker] --source user_choice`? 
- The table has a different title when Tradier is the source. Are Greeks being calculated in a different way here?

**Comment by jmaslek** [comment]
This is a result of yahoo finance giving some wacky chains.  If I look at this AMZN chain, there are some wild values (probably tracking pre split -- note the 2300 strike in the below), and these have IV = 0.  See below.  Since for yahoo, we calculate the greeks on our own (which have values \propto 1/IV, this gives the "Divide by zero")

<img width="1009" alt="Screen Shot 2022-07-31 at 8 05 17 PM" src="https://user-images.githubusercontent.com/18151143/182051116-7af36fbf-1d24-488b-b523-2399baca2e13.png">

> Why does the function not respect load [ticker] --source user_choice?

You mean the menu?  Not sure.  Should just wrap the same load function as the stocks controller.

> The table has a different title when Tradier is the source. Are Greeks being calculated in a different way here?

Yeah I rewrote this yahoo function, including the table recently and didn't touch any tradier functions.  Note that the greeks just get pulled from tradier, so its not the same calculation  (in theory should be comparable if they use a BS model).  Since tradier is not available to all new members, its lifespan is likely not too long here.

The TODOs for a fix on this would be to clean up the options chains and get rid of anything with an IV = 0

**Comment by deeleeramone** [comment]
RE: The split, that is definitely what it is. The contracts are still outstanding, but they are not trading. An easy filter for would be based on the # of 0s in the strike's symbol ID string. 

[ticker]+[yymmdd][c or p][xxxxxxxx] where x is 0-9 and the last two digits are the 1/100th of a dollar. So a filter would sweep [00xxxxxx] where the contracts with two zeroes before a digit are the keepers.
![Screen Shot 2022-07-31 at 6 18 55 PM](https://user-images.githubusercontent.com/85772166/182054846-d52f8ddf-9380-42fe-abf1-1e88b7dd4e3c.png)
