### ISSUE TITLE
[Bug] Installer Only - Economy/FRED function fails: Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2404]
![image](https://user-images.githubusercontent.com/85772166/186252461-3d1397a4-e7ec-4de7-a2d7-aba79bdf07ed.png)

This problem is specific to the installer version. The query portion of the FRED function works, but when requesting a series only this error is returned. The repo version does not have this issue. I have attempted to work around by installing certify in the system default terminal profile shell, but the error persists.

![image](https://user-images.githubusercontent.com/85772166/186252430-280ed50a-b394-4b98-b00c-227ea3643bc3.png)

**Comment by DidierRLopes** [comment]
Yea, just tested using Anaconda and it works as you mentioned

**Comment by DidierRLopes** [comment]
Unrelated but, @deeleeramone when you raise an issue can you make it so that it appears on one line the title? You can write more on the description, but it just makes it more clean in here:
![Screenshot 2022-08-27 at 16 45 53](https://user-images.githubusercontent.com/25267873/187037580-cd09a96b-b4e3-4561-8f71-7c787cb08367.png)

**Comment by hjoaquim** [comment]
@deeleeramone @DidierRLopes I'll close this one as this is a duplicate with #2182
