### ISSUE TITLE
[Bug] hcorr doesn't produce any output

### ISSUE THREAD

**Issue by tinix84** [OpenBB-finance/OpenBBTerminal#2405]
**Describe the bug**
hcorr doesn't produce any output

**To Reproduce**
load USB
ca
getfinviz
hcorr

**Screenshots**
![image](https://user-images.githubusercontent.com/16301528/186264782-d38b9e6c-537c-4b0a-acd5-3f552ca2c714.png)

**Desktop (please complete the following information):**

- OS: wsl
- Python version 3.9

**Additional context**
nothing

**Comment by tinix84** [comment]
if we use the following script 
getfinnhub
hcorr
we get "NaN values found in: FINN, HFBA, HABK.  Backfilling data"

![image](https://user-images.githubusercontent.com/16301528/186265366-3735dd1e-3e18-4abb-b276-b558761be4d9.png)

**Comment by tinix84** [comment]
same effect with getpoly
![image](https://user-images.githubusercontent.com/16301528/186339801-be1f6c6d-574b-45a6-ae0c-8dd4a9828537.png)

**Comment by DidierRLopes** [comment]
![Screenshot 2022-08-27 at 16 38 37](https://user-images.githubusercontent.com/25267873/187037250-f82592c0-cfc3-4e60-a550-f1b6b2438f46.png)

![Screenshot 2022-08-27 at 16 39 31](https://user-images.githubusercontent.com/25267873/187037291-c952cd6c-0c93-43f3-b2d2-ef5ae9ec72cb.png)

The issue is not with the `get` because as you can see they are getting different tickers which are associated with one company. But your `hcorr` command seems to not produce any output. Not sure why, for me it works well.

What version are you on?

**Comment by tinix84** [comment]
SOLVED: 
Add the following to your ~/.bashrc file

export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0
export LIBGL_ALWAYS_INDIRECT=1
GDK_SCALE=1
