### ISSUE TITLE
Allow for more options on chart overlays. 

### ISSUE THREAD

**Issue by Lorenzo025** [OpenBB-finance/OpenBBTerminal#2411]
**What's the feature that should be improved?**
For example i can overlay consumer confidence over the sp500 to draw correlations, but I believe the options are limited to just these two datasets. 

**Describe how you would like the feature improved**
It would be nice to simply give a time frame like 01-01-2001 -- 01-01-2022/ --y1 sp500 --y2 nasdaq. Just as an example. Of course adding more options like gdp overlayed with energy usage would make great use of the overlays. 
![Screen Shot 2022-08-24 at 6 52 50 PM](https://user-images.githubusercontent.com/82773076/186537468-8faa184a-c96f-4356-b52a-c37500a0be70.png)

**Comment by DidierRLopes** [comment]
Hey @Lorenzo025,

You actually can overlay any type of datasets (currently only 2 charts). The trick is that you need to call the datasets so that they are "saved" and then you can call them through the name that appears on the menu. 

If you want to overlay GDP with energy usage that is possible, e.g.

<img width="1425" alt="Screenshot 2022-08-25 at 00 24 35" src="https://user-images.githubusercontent.com/25267873/186540618-e4e19dc1-c185-40a7-a87e-72403385d9ae.png">

This is how I did it:

I used:
`fred -q energy` to query what datasets have the word energy, then I was interested in `PNRGINDEXM`. Thus I run `fred PNRGINDEXM`.

Then I wanted to see if macro command had the gdp so I did, `macro --show parameters` where I saw `GDP` which was when I did `macro -p GDP`.

Then your stored datasets will have the 2 series you are interested,
```
 macro     : United_States_CPI
 fred         : PNRGINDEXM
```
<img width="1062" alt="Screenshot 2022-08-25 at 00 26 52" src="https://user-images.githubusercontent.com/25267873/186540853-8e27b893-8d6e-4e3d-b735-9e5f76dcfd04.png">

So I run `plot --y1 United_States_CPI --y2 PNRGINDEXM`.

Hope this helps!

**Comment by Lorenzo025** [comment]
I see, thank you for that. I wasn't familiar with the -p and that you need to load your parameters first. Having some issues with fred though. enable to get the parameter you refer to here for energy. It might be the API key im using, not sure. 
![Screen Shot 2022-08-27 at 9 16 18 AM](https://user-images.githubusercontent.com/82773076/187031961-dffaffb1-cd50-41f5-a2f7-ae49f53c081d.png)

**Comment by DidierRLopes** [comment]
That is normal, when you select "energy" it basically looks up for all series that contain the term "energy" if that makes sense.

**Comment by Lorenzo025** [comment]
right I was playing with the query option on fred for population and "oil" for example to see what came up. But was having issues pulling the charts up to load. Does this error code have to do with my api key? 

![Screen Shot 2022-08-27 at 9 45 44 AM](https://user-images.githubusercontent.com/82773076/187033018-f8c6ce7c-86be-4773-b7bb-595055bb9a9a.png)

**Comment by DidierRLopes** [comment]
Yes, it seems it does. Mine is working well at least

![Screenshot 2022-08-27 at 15 09 41](https://user-images.githubusercontent.com/25267873/187033865-2c03f5b4-5269-43e9-a301-21488d771064.png)
