### ISSUE TITLE
[Bug] /Stocks/SIA - load function doesn't work. Error: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2684]
Recreate by entering the menu with no stock loaded, then load a ticker from any source. 

<img width="1221" alt="Screen Shot 2022-09-30 at 8 16 50 PM" src="https://user-images.githubusercontent.com/85772166/193384399-9ba34b57-678a-4420-87e0-3d2300cab637.png">

**Comment by catalintoma** [comment]
@deeleeramone I had a quick look at this and it looks like it's intermittent. The first time I loaded I got the same error (it makes no difference if it's loaded before going to `sia` or after).

The reason is that we load this data from Yahoo Finance and the data (which they call `summaryProfile` was missing altogether).

Making it not crash with that error is trivial, but my main question is how should we report this kind of errors? I am very new to this project, but it does look like that menu cannot be used unless we know the sector, country and industry.

A good solution would be to find an alternative source if we can't find it in Yahoo Finance, can someone help me understand if we have an alternative source implemented?

**Comment by DidierRLopes** [comment]
Hmmm, @catalintoma I think you are right. We are relying on the Sector, Industry and Country from Yahoo Finance. This is also because this menu utilizes FinanceDatabase which is built on top of Yahoo Finance.

So I think it is not trivial to use another source in here, unfortunately

**Comment by catalintoma** [comment]
> Has this been fixed? I can't seem to reproduce it.

As I wrote in the first comment, it is **intermittent**
I was able to reproduce for 2-3 times, basically that quote endpoint from YF returns
`summaryProfile: {}`

I want to improve the error message and refactor some duplicate code in that controller tomorrow morning, but as @DidierRLopes said we don't have an alternative source, so not that much we can do.

**Comment by colin99d** [comment]
Sounds good! I was just wanting to replace the NoneType error with a message that is more readable to a non coder.

**Comment by catalintoma** [comment]
@colin99d I've raised PR #2723 for this, can you help with the review?

**Comment by colin99d** [comment]
Done!
