### ISSUE TITLE
[Bug] I'm getting an error while loading stocks

### ISSUE THREAD

**Issue by 12tilak34** [OpenBB-finance/OpenBBTerminal#2719]
![Screenshot (40)](https://user-images.githubusercontent.com/66294702/194167045-e708bf89-6ef9-4889-94ea-387db1e9a357.png)
 
I'm getting some error i don't know what does it mean can anyone help.

**Comment by colin99d** [comment]
@deeleeramone would know more about this, but is something preventing you from accessing yahoo finance?

**Comment by JerBouma** [comment]
@colin99d @12tilak34 This is actually a file from my database, [FinanceDatabase](https://github.com/JerBouma/FinanceDatabase), it looks like you are blocked from accessing GitHub from your computer, is this correct? (for example, do you use a VPN?). This prevents you from accessing the file that is used within the repository.

**Comment by colin99d** [comment]
We can at least handle the error and print a pretty message. Do you know which line of code causes it?

**Comment by 12tilak34** [comment]
@JerBouma @colin99d this there anything apart from VPN which might be blocking the access ??

**Comment by JerBouma** [comment]
We aware that regions in Asia seem to be blocking GitHub. Can you access the file from the browser?

Alternatively, do you use a computer from your work that could be blocking certain domains?

**Comment by 12tilak34** [comment]
@JerBouma what file you are talking about? and i use my personal laptop so i don't think it could be blocking

**Comment by JerBouma** [comment]
It is trying to access this file:

- https://github.com/JerBouma/FinanceDatabase/blob/master/Database/Categories/equities_countries.json
- https://raw.githubusercontent.com/JerBouma/FinanceDatabase/master/Database/Categories/equities_countries.json

But it can not do that because it is blocked by something. So just checking if you can actually see that file in the first place from your browser.
