### ISSUE TITLE
[Bug] No plots in the Web UI version of OpenBB Terminal

### ISSUE THREAD

**Issue by outremont** [OpenBB-finance/OpenBBTerminal#2852]
**Describe the bug**
Whenever I try to produce a plot inside the OpenBB terminal, it is not being displayed.

**To Reproduce**
1. Open BB Terminal UI
2. Type `crypto`
3. Type `load BTC`
4. Type `candle`

**Additional context**
Using docker container as per this tutorial: https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/openbb_terminal/README.md#web-ui---docker

**Comment by deeleeramone** [comment]
https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/openbb_terminal_web

This is because of this: 

![Screen Shot 2022-10-14 at 12 19 20 PM](https://user-images.githubusercontent.com/85772166/195924943-d4430056-3ec6-4029-b90d-99aacd143110.png)

Sounds like a great #hacktoberfest challenge though!

**Comment by outremont** [comment]
Oh, I see! Thanks
