### ISSUE TITLE
[Improve] stocks/ca/ticker doesnt seem to add to list

### ISSUE THREAD

**Issue by jmaslek** [OpenBB-finance/OpenBBTerminal#2957]
If I do
```
ticker msft
set aapl,amzn
```

Then any command only gets data for aapl/amzn, not msft

**Comment by DidierRLopes** [comment]
This is actually not a bug - we discussed this in the past.

`ticker` affects what you want to use to get `similar companies`. Whereas `add`, `set` and `rmv` correspond to the list of tickers.

Since we are going to merge the `gets` into 1 command, I'd say that that `ticker` command can be removed and become an argument

<img width="819" alt="Screenshot 2022-10-22 at 01 40 25" src="https://user-images.githubusercontent.com/25267873/197308636-cc9394cd-9ad3-42f8-8913-cc3ce3b29d0f.png">
