### ISSUE TITLE
[Bug] Autocomplete

### ISSUE THREAD

**Issue by jmaslek** [OpenBB-finance/OpenBBTerminal#3128]
@DidierRLopes why this no work?
in forex
type:
load E
-- nothing pops up from the list 

type load -t E and it pops up

**Comment by jmaslek** [comment]
happens in `sia/clear m`

**Comment by Chavithra** [comment]
historical --help doesn't work unless --ticker is provided.

**Comment by DidierRLopes** [comment]
It's working for me. But when you start typing with the argument, the list of options disappears

<img width="437" alt="Screenshot 2022-11-01 at 09 17 44" src="https://user-images.githubusercontent.com/25267873/199202887-447a622f-c1fe-4f75-8628-b0aa317f734c.png">

<img width="427" alt="Screenshot 2022-11-01 at 09 17 38" src="https://user-images.githubusercontent.com/25267873/199202893-24b7c939-f45d-45ba-92aa-0da0c213cf3b.png">

<img width="420" alt="Screenshot 2022-11-01 at 09 17 31" src="https://user-images.githubusercontent.com/25267873/199202894-b7e3dd2c-b3bb-4d46-83ea-2d6b9a4ccfa3.png">

I get the same on curve, I think this may be a hard thing to fix. But I can look into it!

**Comment by andrewkenreich** [comment]
go to crypto/ov

and do cr borrow

and select it the first time - it works fine then do cr again and it works fine

but now...do cr borrow - and dont select it and type our borrow fully

then do cr again

and nothing pops up


This happens across the full terminal I believe whenever you type out the auto complete instead of selecting
