### ISSUE TITLE
[FR] Use CPU only

### ISSUE THREAD

**Issue by WyattLiu** [OpenBB-finance/OpenBBTerminal#322]
**What's the problem of not having this feature?**
GPU VRAM is limited in some cases so I need to hotswap to CPU

**Describe the solution you would like**
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

in cmd: we could have like lstm --force_tf_cpu to turn that switch, default is using CUDA where needed.

**Describe alternatives you've considered**
I am able to set that in the shell, I even did rename cuda dir to confuse tf to hard disable it.

**Comment by DidierRLopes** [comment]
Hey @WyattLiu, is this something you could do?

We're always extremely keen on external contributions :)

Otherwise we'll have a look at this sooner or later!

**Comment by piiq** [comment]
This was resolved by #1933 We now are CPU-only and according to benchmarks this works faster than GPU because of the size of the datasets


And a comment unrelated to this issue:
Hey @deeleeramone, check this out, github supports mp4

https://user-images.githubusercontent.com/11668535/197819468-ef27be9b-ee1c-4b8c-a4f0-0151a855d471.mp4
