### ISSUE TITLE
[Bug] `equity` and `forex` default reports breaking

### ISSUE THREAD

**Issue by hjoaquim** [OpenBB-finance/OpenBBTerminal#3235]
Equity:

![image](https://user-images.githubusercontent.com/48914296/199218599-1c669e01-6351-43da-8eca-7dbb4156edc5.png)

Forex:

![image](https://user-images.githubusercontent.com/48914296/199218630-fe1d60fa-f40f-4142-938a-af89e9214386.png)

**Comment by obydog002** [comment]
Ill look into this!

**Comment by obydog002** [comment]
Hey, that PR only fixed the equity report error BTW. The forex one was giving me an entirely separate error that remains unaddressed. I was looking into the Equity one first. @colin99d

**Comment by colin99d** [comment]
Oh shoot, when I renamed from fixed I thought this would not close. Thanks for noticing this.

**Comment by obydog002** [comment]
Report fails to generate because a cast fails
![forex_report_error](https://user-images.githubusercontent.com/38587157/200258912-255a9396-2e42-4bf0-90f9-a0cf545fba31.png)
The culprit is in forex_helper.py in the load function
![forex_helper_load_error](https://user-images.githubusercontent.com/38587157/200259295-867b1a12-0906-49ee-9466-2805634deb7a.png)
Having a look at load in stocks_helper.py, it doesn't seem like intervals higher than 1 day are supported? Not sure how to fix this other than changing the interval amount in the report generation.
