### ISSUE TITLE
[Bug] resetting not possible / crashes terminal

### ISSUE THREAD

**Issue by mknudsen** [OpenBB-finance/OpenBBTerminal#3383]
The app crashes when returning from lots of submenus.

**To Reproduce**

Open terminal, navigate to submenus, navigate back with 'r'.

![Screenshot 2022-11-11 at 09 29 32](https://user-images.githubusercontent.com/564654/201298658-7348e38a-7ae5-49c8-9118-ebc32100b79b.png)

Looks to me like the directory is wrong, the app resides in `/Applications/OpenBB\ Terminal` not in `/Applications/OpenBB`.
- OS: Mac 13.0.1 (22A400)
- OpenBB Terminal v1.9.0
- Python version 3.10.8

**Comment by colin99d** [comment]
Thank you for reporting this bug. @DidierRLopes since the reset feature is only for development should we remove it from the installer? @mknudsen is there a use case you had for this? It is meant to help us develop the terminal, but it is buggy and leaks memory, so I personally dont think it should be included in the installer build, but if there is a place its really helpful I can understand.

**Comment by DidierRLopes** [comment]
> Thank you for reporting this bug. @DidierRLopes since the reset feature is only for development should we remove it from the installer? @mknudsen is there a use case you had for this? It is meant to help us develop the terminal, but it is buggy and leaks memory, so I personally dont think it should be included in the installer build, but if there is a place its really helpful I can understand.

Yes, absolutely. We should only add it to the controller choices if it's not an installer.

I wouldn't say it is buggy, as it is doing what it is supposed to do. Which is basically run the terminal script again with the code changes. But this is only useful for development as otherwise there's no need to reset the app.

@mc

**Comment by jmaslek** [comment]
This is actually the intended behavior, so will close until a further bug is discussed.
