### ISSUE TITLE
[Bug] #3180 might not work on python 3.8

### ISSUE THREAD

**Issue by Chavithra** [OpenBB-finance/OpenBBTerminal#3394]
We need to check if #3180 work properly in python 3.8.

**Comment by linagee** [comment]
When trying to select the menu option "forecast", I get the error:
`Error: 'type' object is not subscriptable`
which happens at:
https://github.com/OpenBB-finance/OpenBBTerminal/blob/v2.0.0/openbb_terminal/forecast/helpers.py#L467
This is caused by me using Python 3.8.10
https://stackoverflow.com/questions/63460126/typeerror-type-object-is-not-subscriptable-in-a-function-signature

I don't see any existing Python version checking in OpenBBTerminal.

**Comment by jmaslek** [comment]
@Chavithra -- does this need to be investigated further?
