### ISSUE TITLE
[Bug] SDK - `openbb.crypto.price` - TypeError: cannot unpack non-iterable coroutine object

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3481]
`price,confidence,previous = openbb.crypto.price('ETH')`

![Screenshot 2022-11-18 at 10 57 44 AM](https://user-images.githubusercontent.com/85772166/202781838-a6c23c1a-a45f-4071-ba49-645fa899658a.png)

```
/var/folders/46/0mj4kf1j4fd17n7j2fr9296w0000gn/T/ipykernel_41342/3775975678.py:1: RuntimeWarning: coroutine 'get_price' was never awaited
  price,confidence,previous = openbb.crypto.price('ETH')
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [33], line 1
----> 1 price,confidence,previous = openbb.crypto.price('ETH')

TypeError: cannot unpack non-iterable coroutine object
```

**Comment by northern-64bit** [comment]
The issue with the command is that it is a async function, which makes that it need special treatment. So you can get the function to work with a few extra steps:
```python import asyncio
async def a():
    return await openbb.crypto.price('ADA-USD')
a()
b = await asyncio.gather(a())
price, confidence, previous = b[0]
print(price, confidence, previous)
```
This issue can be solved be creating a new function for the SDK, which does something similair to the code above.
![image](https://user-images.githubusercontent.com/75195383/202891857-c8c21f8f-fe85-4d86-86ee-8b5b93354143.png)
[Note: ETH is not a valid input to the function]

**Comment by northern-64bit** [comment]
The command has to be run with await (in jupyter notebook):
`price, confidence, previous = await openbb.crypto.price("ADA-USD")`
My previous comment was a bit unclear and overcomplicated. There is no method (known to me) to create a "regular" function from an asyncio function which should be able to run in jupyter notebook and normally: https://stackoverflow.com/questions/55409641/asyncio-run-cannot-be-called-from-a-running-event-loop-when-using-jupyter-no

There is a solution which should work when running the code generally but we don't want to restrict the usage of the command. So when in jupyter notebook just use `await` and otherwise use `asyncio.run(openbb.crypto.price("ADA-USD"))`.
