### ISSUE TITLE
[Bug] Windows installer: splash screen is displayed while report is being executed

### ISSUE THREAD

**Issue by montezdesousa** [OpenBB-finance/OpenBBTerminal#3503]
**Describe the bug**
While reports menu is executing a report, the OpenBB start up splash screen is thrown into top of screen.

![image](https://user-images.githubusercontent.com/79287829/203082516-58c07d06-39cc-4326-acb4-c245703da44c.png)

OS: Windows 11 Home

**Comment by CaptainTollBooth** [comment]
I have a similar situation, but slightly different.
Upon loading the Terminal, the splash screen appears and stays fixed in the centre of the screen.
Started to see this after the upgrade to 2.0 from the previous version. (Windows 10)

![image](https://user-images.githubusercontent.com/53947682/206600936-2241a3d0-26ac-4b50-90a3-2f31efd170ba.png)
