### ISSUE TITLE
[IMPROVE] Portfolio Optimization SDK

### ISSUE THREAD

**Issue by minhhoang1023** [OpenBB-finance/OpenBBTerminal#3616]
# Problem 
In the portfolio optimization menu, there are two ways you can perform optimization techniques:

1. Using the Portfolio engine
2. Passing a list of symbols directly 

The second way is currently not optimal. Even though you can obtain the optimized portfolio weights, you cannot utilize other essential features such as plotting risk contribution, or asset cluster map. 

This is because the `plot` command requires metadata such as `Sector`, `Asset Class`, `Industry`. 

<img width="939" alt="image" src="https://user-images.githubusercontent.com/40023817/204188394-e29843d5-9295-47df-a0c0-fd18f7d5f495.png">

# Solution 

We should not **stop supporting the option to provide symbols directly** to the optimization methods.

In case users want to provide the list of symbols directly and not through a file, **they also need to provide all required metadata (e.g. Sector, Asset Class, Industry)**. Otherwise, it won't work for many essential commands.

**Comment by JerBouma** [comment]
> We should not stop supporting the option to provide symbols directly to the optimization methods.
>
> In case users want to provide the list of symbols directly and not through a file, they also need to provide all required metadata (e.g. Sector, Asset Class, Industry). Otherwise, it won't work for many essential commands.

Thought about this and I would say that files (let it be Excel or JSON) should be almost mandatory. We can give them the option to indeed provide all the info directly though metadata (so they could in essence use for example JSON files or any other format) but due to the complexity of these materials it makes sense that generally you use an Excel file.

So concluding, I agree with you :)

**Comment by montezdesousa** [comment]
I think this is already in place since https://github.com/OpenBB-finance/OpenBBTerminal/pull/3582. I think this implements your idea, like we spoke last week, but tell me what you think.

So now if you to pass symbols directly you can't. You are required to provide the symbols and the metadata if you don't use the file template.

```
    Examples
    --------
    >>> from openbb_terminal.sdk import openbb
    >>> d = {
                "SECTOR": {
                    "AAPL": "INFORMATION TECHNOLOGY",
                    "MSFT": "INFORMATION TECHNOLOGY",
                    "AMZN": "CONSUMER DISCRETIONARY",
                },
                "CURRENCY": {
                    "AAPL": "USD",
                    "MSFT": "USD",
                    "AMZN": "USD",
                },
                "CURRENT_INVESTED_AMOUNT": {
                    "AAPL": "100000.0",
                    "MSFT": "200000.0",
                    "AMZN": "300000.0",
                },
            }
    >>> p = openbb.portfolio.po.load(symbols_categories=d)
    >>> weights, performance = openbb.portfolio.po.dividend(portfolio_engine=p)

    >>> from openbb_terminal.sdk import openbb
    >>> p = openbb.portfolio.po.load(symbols_file_path="~/openbb_terminal/miscellaneous/portfolio_examples/allocation/60_40_Portfolio.xlsx")
    >>> weights, performance = openbb.portfolio.po.dividend(portfolio_engine=p)
```

**Comment by minhhoang1023** [comment]
alrighty, @montezdesousa was super fast and implemented this immediately when we spoke last Friday. I'll close this.
