### ISSUE TITLE
[Bug] ETF/search --export. Error: 'dict' object has no attribute 'replace'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3654]
`/etf/search` fails to export.

```
Error: 'dict' object has no attribute 'replace'
```

![Screenshot 2022-11-29 at 9 03 56 AM](https://user-images.githubusercontent.com/85772166/204594775-498a5d51-e73c-406d-bbc6-a5e38a6b0f7a.png)

**Comment by victortangggg** [comment]
seems like the reason is because the data type that is passed in as parameter for `export_data(...)` is of dict while it is expected to be of data type pd.dataframe

![image](https://user-images.githubusercontent.com/23350634/204613495-f779d261-c2c2-43c3-8b9e-2e02a35620d0.png)

in `export_data` the parameter was handled as dataframe
![image](https://user-images.githubusercontent.com/23350634/204613623-4cb76e4b-4063-4c42-97d2-274c250c78bd.png)


**suggestion**
replace `data` with `table_data_sorted`
![image](https://user-images.githubusercontent.com/23350634/204613911-36c4d99a-79ac-4baa-9adf-4aa5329fa5c6.png)

**Comment by victortangggg** [comment]
happy to commit the change and create a pull request if there's no issue.

**Comment by jmaslek** [comment]
> happy to commit the change and create a pull request if there's no issue.

Feel free to do so!

**Comment by victortangggg** [comment]
PR created under https://github.com/OpenBB-finance/OpenBBTerminal/pull/3664
please let me know if im doing this correctly thanks!
