### ISSUE TITLE
[IMPROVE] Optimization methods progress bar

### ISSUE THREAD

**Issue by montezdesousa** [OpenBB-finance/OpenBBTerminal#3686]
Currently while running an optimization method the user has to wait without any idea of how far from done is the optimization procedure. Instead of the current message "Optimization can take time. Please be patient..." we could add some progress bar that updates along the way.

<img width="438" alt="Screenshot 2022-12-02 at 10 34 47" src="https://user-images.githubusercontent.com/79287829/205273536-06d9a268-60dd-420d-9c09-36ca73873ce7.png">

**Comment by jmaslek** [comment]
This has been asked before.  I dont think there is a solid progress bar solution due to the nature of convex optimization.

CVXPY does have a `verbose=True` option in their solve, but this would require changing the riskfolio source code (and it is hard to interpret the output of the verbose as well.

**Comment by montezdesousa** [comment]
> This has been asked before.  I dont think there is a solid progress bar solution due to the nature of convex optimization.
> 
> CVXPY does have a `verbose=True` option in their solve, but this would require changing the riskfolio source code (and it is hard to interpret the output of the verbose as well.

Alright, makes sense. If I understood correctly, we could have some idea of how close we are from the solution tolerance then? Just to make it more responsive idk
