### ISSUE TITLE
[Bug] Intel Mac & Some Windows Terminal Users are Reporting Forecast and Portfolio Menus Hangs

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3695]
I can't recreate, but a pattern is emerging here. They report that entering the menus causes the terminal to hang. One user reported that after two minutes, this error message was printed:

`"There was an error connecting to the API. Please try again later."`

This error message is printed by the FinViz API - notably when the screener is dead and revives itself by repeating the command - but there should be no reason why it is being encountered without running any commands.

The SDK is, at least by one account, not affected.

**Comment by deeleeramone** [comment]
This problem is being reported from both, the installer, and, pip install versions.

**Comment by deeleeramone** [comment]
Two of the machines reporting this error:

```
MacBookPro CPU version: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz.
MacBookPro16,1, Intel Core i9 8 core, 2.4 ghz
```

**Comment by gsbabra123** [comment]
I have a similar issue where the "Stocks" menu hangs and returns "There was an error connecting to the API. Please try again later" after a couple of minutes.
The stocks menu has not been opening for me for the last 3 days. 
reinstalling hasn't fixed the issue.
I am on windows using the installer. Intel i3 12100F cpu. 
![openbb](https://user-images.githubusercontent.com/114330275/205840105-27eda3e8-1970-4a3b-9d4d-f5d4384f85b2.JPG)

**Comment by deeleeramone** [comment]
Another user with Mac Intel installer:

```
MacBook Air (13-inch, 2017) 

OS Version - macOS Monterey, Version 12.6.1 (21G217)

Processor Type - 1.8 GHz Dual-Core Intel Core i5
```

**Comment by JerBouma** [comment]
> I have a similar issue where the "Stocks" menu hangs and returns "There was an error connecting to the API. Please try again later" after a couple of minutes. The stocks menu has not been opening for me for the last 3 days. reinstalling hasn't fixed the issue. I am on windows using the installer. Intel i3 12100F cpu. ![openbb](https://user-images.githubusercontent.com/114330275/205840105-27eda3e8-1970-4a3b-9d4d-f5d4384f85b2.JPG)

Hi @gsbabra123, this issue occurs because it will try to collect data from the FinanceDatabase repository once it starts up the Stocks menu, I've made a PR to correct this here: https://github.com/OpenBB-finance/OpenBBTerminal/pull/3762. If you are familiar with Python and Git, I invite you to pull this Pull Request an test if this indeed fixes the issue for you. 

`There was an error connecting to the API. Please try again later.` is an error message we built in directly into the code and in the PR I show that this is indeed related to the FinanceDatabase. See line 77-79 here: https://github.com/OpenBB-finance/OpenBBTerminal/blob/5a43a2af5a2d96a339863a5a06309db90f60597f/openbb_terminal/stocks/stocks_controller.py.

Alternatively, you can see if you can access this file: https://raw.githubusercontent.com/JerBouma/FinanceDatabase/master/Database/Categories/equities_countries.json. This is unfortunate not a fool-proof method since it doesn't completely replicate the method used in the installer of Python version but it gives a good indication.

Can I ask you whether you are using a work computer, in what country you are based and whether you use a VPN anywhere?

**Comment by jmaslek** [comment]
I am pretty sure this got ironed out last year

**Comment by JerBouma** [comment]
@jmaslek Yes, I was waiting for confirmation from any of them but we received no more complaints so I guess it is fixed.
