### ISSUE TITLE
[IMPROVE] Increase the speed behind loading stock data

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3699]
I believe that `additional_info_about_ticker` function is responsible by most of this lag. I personally don't use that quick overview and find it annoying that it takes me this long to load data because of it. I think for default it shouldn't.

See quick inspection below,
<img width="762" alt="Screenshot 2022-12-04 at 13 14 00" src="https://user-images.githubusercontent.com/25267873/205492568-3df73105-341d-47e6-aa22-f13a7e926ea6.png">

**Comment by victortangggg** [comment]
hey @DidierRLopes I found a potential solution:

I see that the bottleneck is in the API call. By using `yf.Ticker(ticker).stats()` instead of `yf.Ticker(ticker).info`, the time taken is cut significantly
![image](https://user-images.githubusercontent.com/23350634/205508297-ff90c0f4-9ae0-4b48-82b0-6309bdf0ab5e.png)
![image](https://user-images.githubusercontent.com/23350634/205508315-2933efe1-37f7-4117-9ac8-8463efb2b0f9.png)

this is backed up by a closed issue from the yfinance project - https://github.com/ranaroussi/yfinance/issues/851

let me know what you think. I will create a PR if team is happy with it.

**Comment by DidierRLopes** [comment]
Hey @victortangggg,

I didn't know this! This is definitely an improvement!

Yes, please. Feel free to go ahead with the fix :)

**Comment by victortangggg** [comment]
thanks! PR is here - https://github.com/OpenBB-finance/OpenBBTerminal/pull/3700
