### ISSUE TITLE
[Improve] Equity report outputs income in local currency

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3704]
User request: convert financials to USD

@jmaslek not sure if this is an enhancement, is more of a request really.

**Comment by JerBouma** [comment]
Note that this only applies to scenarios where you include a ticker with a different exchange. E.g. if I would use `ASML` no harm is done even though this is a Dutch company. This is because these tickers default to the US market. This is a very specific case in which you would use for example `ASML.AS`.

Also note that it requires to get different exchange rates at different times, you can not convert the whole financial statement in dollars with the current rate.
