### ISSUE TITLE
[Bug] Forecast/Plot - Multiple Columns Doesn't Work

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3791]
`/stocks/load AAPL/forecast/plot -v AAPL.high,AAPL.low`

```
(🦋) /forecast/ $ plot -v AAPL.high,AAPL.low

usage: plot [-v {AAPL.date,AAPL.open,AAPL.high,AAPL.low,AAPL.close,AAPL.adj_close,AAPL.volume}] [-h] [--export EXPORT]
plot: error: argument -v/--values: invalid choice: 'AAPL.high,AAPL.low' (choose from 'AAPL.date', 'AAPL.open', 'AAPL.high', 'AAPL.low', 'AAPL.close', 'AAPL.adj_close', 'AAPL.volume')
```

**Comment by jmaslek** [comment]
This is because we specify choices in the parser.  Passing a csv list is not a valid "choice". Getting rid of that line will fix this issue, but then auto complete won't work.  @martinb-bb will leave decision to you how to handle, but this should port over to econometrics as well.

**Comment by martinb-bb** [comment]
I have been thinking about this... Perhaps will have to remove autocomplete for this function on the menu because we have another parameter `--past-covariates` that takes in a list that works fine. 
<img width="659" alt="image" src="https://user-images.githubusercontent.com/105685594/208958348-c64bfc63-88ba-4591-8f3b-26f77444d5c5.png">

**Comment by colin99d** [comment]
@martinb-bb, how do we want to handle this?

**Comment by martinb-bb** [comment]
@colin99d perhaps with what I mentioned above?
