### ISSUE TITLE
[FR] Add column styling to print_rich_table

### ISSUE THREAD

**Issue by marcelonyc** [OpenBB-finance/OpenBBTerminal#3879]
**What's the problem with not having this feature?**
In my use case, I wanted `print_rich_table` to display one of the column's values fully (not truncated). Another case is conditional formatting.   

**Describe the solution you would like**

**Expose add_column arguments**
The easiest way to expose this functionality would be to add a column styling parameter (arguments to [add_column](https://rich.readthedocs.io/en/stable/reference/table.html?highlight=add_column#rich.table.Table.add_column)) But, since column styling impacts the look and feel of the terminal this might not be ideal.

Something like
```
styling_dict = {"col_name" : { "width":33.....}
print_rich_table(...,colmun_styles=styling_dict)
```

I can think of other ways to implement this, but they would require fundamental changes, like making print_rich_table a class with more properties. So, food for thought, how can column styling be added?

**Comment by jmaslek** [comment]
One non-ideal thing we have done is using textwrap directly on the df in the view function so that it displays in one cell but on multiple columns.  Doesn't exactly solve your problem (we will always have someone like me that uses the smallest possible terminal window), but this will show in a cell of fixed width:
```
df.apply(lambda x: "\n".join(textwrap.wrap(x, width=XX))
```
