### ISSUE TITLE
[Bug] Can't access certain crypto.dd functions from SDK

### ISSUE THREAD

**Issue by djl0** [OpenBB-finance/OpenBBTerminal#3884]
Apologies if I'm just missing something, but I cannot seem to access crypto dd `score` and `dev` from the SDK. They do not appear in `dir(openbb.crypto.dd)`. I'm having a hard time tracing this back with the Breadcrumbs() structure. Given they appear in `due_diligence_api.py` I would have expected them to be accessible.

Thanks!

**Comment by jmaslek** [comment]
Yup.  Nice catch.  These have not made their way in.  They need to be mapped to their model functions in `miscellaneous/library/trail_map.csv`.

We are still dotting our i's and crossing our t's with getting every terminal function mapped, so thanks for helping us stop some more!

**Comment by jmaslek** [comment]
So actually I am seeing most of the cg functions in crypto.dd aren't in the sdk and the reason is that they aren't following the MVC convention and these functions actual do the model functions in the view, so we dont have the correct way of mapping to the model -- because there is no model.

This will need a little more than a quick patch.  @Chavithra @jose-donato
