### ISSUE TITLE
[IMPROVE] OpenBB SDK via Docker

### ISSUE THREAD

**Issue by Marx2** [OpenBB-finance/OpenBBTerminal#4061]
**What's the feature that should be improved?**
Installing OpenBB SDK is complicated.

**Describe how you would like the feature improved**
It would be very helpful to make installing process much easier. 

**Possibly describe the ideal way to improve this**
ideally, there should be Docker image with all dependencies built in, which can be easily download on desktop or even Kubernetes. Ideally, OpenBB SDK should expose REST/GraphQL endpoints.

**Comment by Marx2** [comment]
Can I ask for a piece of information, how it's resolved?

**Comment by piiq** [comment]
Hi @Marx2 
Since v4 has been released in November 2023, the OpenBB Platform (the successor of the SDK) does exactly what you have been asking for in this issue. So the issue has actually been resolved over 6 months ago and closing this issue is just a clean-up.
Please refer to the docs here https://docs.openbb.co/platform/installation#docker
