### ISSUE TITLE
Forex candle graph show two different timelines after a quote command

### ISSUE THREAD

**Issue by eonvdk** [OpenBB-finance/OpenBBTerminal#4112]
**Describe the bug**
Same /candle command show to different historical timelines on the graph if I run a /quote command in between the /candle commands

**To Reproduce**
Terminal 2.3.0
/forex - load USDRON
/candle - shows historical data since Feb 2022.
after that I use /quote and when I use /candle again - the graph shows me data only since Jan 30 2023

**Desktop (please complete the following information):**

- OS: macOS 12.6
- Python version 3.9

Added video to show the result

**Comment by piiq** [comment]
Thanks for the issue

I see why that is happening. This is because load and quote are using different data sources to fetch the price data and when you run quote the price data you have loaded into the terminal is being overwritten with data from a different data provider that has different default time range.

How would you suggest changing this behaviour?
