### ISSUE TITLE
[Bug] stocks-overview throws an error Namespace object has no attribute 'source'

### ISSUE THREAD

**Issue by kajdo** [OpenBB-finance/OpenBBTerminal#4285]
**Describe the bug**
tried to check the overview report with loaded jnj

**To Reproduce**
stocks/load jnj/overview

**Screenshots**
![image](https://user-images.githubusercontent.com/8735942/219900586-f98c27bb-edf1-4d87-b3e1-ca64d18e5515.png)

**Desktop (please complete the following information):**

- OS: Linux mint 5.15.0-56-generic
- Python version 3.10.6

**Comment by deeleeramone** [comment]
What is the version number you have? If you haven't already, update the packages as well because many version bumps have occurred since 2.3, `poetry install -E all`

![Screenshot 2023-02-18 at 9 53 24 PM](https://user-images.githubusercontent.com/85772166/219931491-34305d3f-71eb-4b68-9633-d34432fc3c55.png)

![Screenshot 2023-02-18 at 9 53 56 PM](https://user-images.githubusercontent.com/85772166/219931516-77c90a31-ddd7-472b-adb7-f4dbd9b7bd10.png)

![Screenshot 2023-02-18 at 9 54 56 PM](https://user-images.githubusercontent.com/85772166/219931554-a9b45d5f-f6e5-44c3-8c5f-51db7096cef2.png)

**Comment by kajdo** [comment]
I should be on the current version -- did a fresh install
![image](https://user-images.githubusercontent.com/8735942/219969649-6598ec96-ce8f-45b2-855b-ef644dd47a98.png)

but you're right -- removed my datasources from the user directory and it works again ... think it was some legacy config from new years yf issue where I tried to change datasources to get openbb up and running
