### ISSUE TITLE
[IMPROVE] Plotly improvement suggestions

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#4376]
Given that we have legends, we don't need to put the label in the point floater as well. It gets cutoff anyways and you can't read any of it.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/46355364/222462741-d7314bc9-5f8c-44c5-a485-6e2af8d5637c.png">

Also note the mistake within `economy/macro` here where it says the `unemployment` in both the legend and title. It also no longer specifies the units. This could be resolved with setting y-axis label based on the parameter.

About buttons:
- The downloads of plots shouldn't be happening in the current location, this needs to be done in the OpenBBUserData folder.
- The text when exporting the image is wrong "`Fished downloading to `" and is missing the location.
- The download raw data button does nothing for me. 
- What does "Upload Image" do?

**Comment by tehcoderer** [comment]
How's this?
![image](https://user-images.githubusercontent.com/61340027/222526631-b635e599-6952-471f-be78-e18baed6faef.png)

Since we're downloading the plot inside of pywry window which is a web browser it handles the path. 
If you do `--export png` it downloads to the OpenBBUserData folder.

Mmmm that's weird for me that print shows the path
![image](https://user-images.githubusercontent.com/61340027/222526881-2f249580-b4fb-4102-9c93-ee134a679e28.png)

Can you set `DEBUG_MODE=True` env and see what pywry backend prints?

**Comment by JerBouma** [comment]
@tehcoderer 

I see no reason to include the label in the ticks as we have a legend for that (that's always included). I'd really suggest getting rid of it as it doesn't add value.

And awesome! Make sure that this work for both the raw data exports and plot exports. People will otherwise not be able to find the files.

**Comment by tehcoderer** [comment]
@JerBouma already [merged](https://github.com/OpenBB-finance/OpenBBTerminal/commit/94e2b33802c32e9a4637af95633fcfe900f7f320#diff-ff26ce8470a81fb216d7c712638557fb85e3e57587cf5d29d16733daa3e1618f) no labelsss 😉

the raw data and exports path remained unchanged, when inside of the window was the tricky one lol. 

Pull dev and `pip install pywry -U --force-reinstall`
