### ISSUE TITLE
[IMPROVE] Remove the setting for `tbnews`. Nobody can use it.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4724]
Twitter doesn't even know what is happening with their API, and all this "setting" does is tempt users to enable it.  Nobody can  apply get access to it on a free level, and they don't even know how much it costs if you wanted to pay.

**Comment by BeGreifen** [comment]
I accidentally enabled the twitter news in the setting, 
before enabeling the API in the keys -  since then openBB crashes when I start it. with the message : 
tweepy.errors.Unauthorized: 401 Unauthorized 
89 - Invalid or expired token.
[23544] Failed to execute script 'terminal' due to unhandled exception!

can anyone give me a hint how to undo the settings.

**Comment by BeGreifen** [comment]
I found the file as discribed in the link at the end of my message
the flare setting can be found:
\[userdir}\.openbb_terminal\.env

the .openbb_terminal directory is hidden

https://github.com/OpenBB-finance/OpenBBTerminal/issues/4722#issuecomment-1501114348
