### ISSUE TITLE
[Bug] Log handling on login/logout

### ISSUE THREAD

**Issue by hjoaquim** [OpenBB-finance/OpenBBTerminal#4800]
Replicate (wrong) current behavior:

1. enter the terminal on guest mode: `openbb`
2. type any command so it's easier to track: `stocks/load gme/`
3. login: `account/login`
   At this moment, if you navigate to the logs' directory, you should have 4 files. 
   The 2 most recent should contain logs from the new session (i.e., after the login only, but you'll notice that there are commands from the last session (namely the `stocks/load gme/`)
   Also, if we keep using the terminal, you'll notice that new commands will be written both the logs from current session and the older one.

**Comment by montezdesousa** [comment]
After some debugging the issue seems to be on `log_terminal` is called inside `terminal()`. This function is adding new log handler files every time it is called.

We call it on `login` and on `reset` at least, so the logs are written in both files. If we run `reset` 5 times it will create and write into 5 different log handler files.
