### ISSUE TITLE
[Bug] `stocks/ba/` - Reddit functions - Error: Maximum recursion level reached.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4943]
This is the output of, `/stocks/ba/spacc`, when no ticker is loaded.

![Screenshot 2023-05-01 at 1 09 11 PM](https://user-images.githubusercontent.com/85772166/235522366-a6e505dc-5ac3-4fbc-abb6-178d1992b564.png)

IPO is likely referring to, Initial Public Offering, and is not a ticker.  The printed sentence, itself, does not really make sense. What does being mentioned more than once across the previous SPACs even mean?

```
The following stock tickers have been mentioned more than once across the previous SPACs:
2 SOFI, 2 BTDR, 2 IPO, 2 YOU, 2 STKH
```

**Comment by LOne2three** [comment]
Its calling the reddit API for r/SPACS, and the 'tickers' are combed from the reddit posts. My guess is that it might have gotten non ticker abbreviations in the mix when no ticker is loaded

**Comment by deeleeramone** [comment]
What does "previous SPACs" mean? That is the confusing part.. are we talking about previous Special Purpose Acquisition Companies, or are we talking about a previous post in r/SPACs.

It doesn't actually know how to differentiate between a ticker and an abbreviation. DTE, OTM, ITM, etc. get returned as ticker results all the time.  The error is also not exclusive to this function. 


![Screenshot 2023-05-01 at 4 09 22 PM](https://user-images.githubusercontent.com/85772166/235546879-a8f448dd-e8ad-4748-ac4e-006fe89779ba.png)

**Comment by LOne2three** [comment]
> What does "previous SPACs" mean? That is the confusing part.. are we talking about previous Special Purpose Acquisition Companies, or are we talking about a previous post in r/SPACs.
> 
> It doesn't actually know how to differentiate between a ticker and an abbreviation. DTE, OTM, ITM, etc. get returned as ticker results all the time. The error is also not exclusive to this function.
> 
> ![Screenshot 2023-05-01 at 4 09 22 PM](https://user-images.githubusercontent.com/85772166/235546879-a8f448dd-e8ad-4748-ac4e-006fe89779ba.png)

I have looked at the code and it seems like 'spacs' refers to  the top 10 most popular reddit posts in r/spacs. I also found the part of the code which is causing the function to return non ticker abbreviations. It is a regex issue as the function is looking for  all abbreviations between 3-5 characters in length

**Comment by the-praxs** [comment]
On the `develop` branch, I get the following error - 
![image](https://user-images.githubusercontent.com/88149434/236412072-39911b92-2169-448d-a5b8-49a59d8114a0.png)

But on the release app, I get this error - 
![image](https://user-images.githubusercontent.com/88149434/236412245-631c8e27-c2ba-4fd7-a068-f46b005d839d.png)

**Comment by LOne2three** [comment]
Invalid object at position 0 is probably caused by transposing the columns into a dataframe.  I am not sure about the recursion error but it might be related to the dataframe issue because the recursion error seems to have been replaced by the invalid object at position 0 error for me even though I previously got the recursion error on the main branch so the error seems likely to be caused by the dataframe.

**Comment by LOne2three** [comment]
I have fixed the errors. I will send a pull request once I do more tests. The non ticker abbreviations were coming through occasionally because too many requests were made to finviz as the calls were made in a for loop, and type error and recursion error were caused by column type mismatch when converting the dataframe into a table using the plotly backend.

**Comment by the-praxs** [comment]
@LOne2three Is this fixed and pushed to PR?

**Comment by LOne2three** [comment]
> @LOne2three Is this fixed and pushed to PR?

Yes @jmaslek is reviewing the pull request.
