### ISSUE TITLE
[Bug] Reports/economy: Report fails at `openbb.economy.treasury_chart()` - Error: 'list' object ahs no attribute 'columns'

### ISSUE THREAD

**Issue by coys997** [OpenBB-finance/OpenBBTerminal#5207]
**Describe the bug**
Running the 'economy' report under reports throws the following error:

An error was encountered in cell [1], check the notebook:
/home/$USER/OpenBBUserData/reports/20230708_170659_economy.ipynb

**To Reproduce**
1. Launch OpenBBTerminal 3.1.0
2. Open reports
3. Run the economy report
4. Error is thrown against cell 1 in the notebook as above.

**Screenshots**
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/121838606/9ee365ae-d578-47dc-9d51-f53912964710)

**Desktop (please complete the following information):**

- OS: Mint 21
- Python version 3.10.6

**Additional context**
Can provide the .ipynb generated as needed.

**Comment by deeleeramone** [comment]
Hello,

This issue was resolved by #5181.  Although I now see a new error.

![Screenshot 2023-07-10 at 11 46 45 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/c4e8e95f-4e17-46f9-a190-833657b91101)
![Screenshot 2023-07-10 at 11 51 19 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/721b2fe6-4ef2-4c4f-9ca9-7f2b28161dbc)
