### ISSUE TITLE
[Bug] Bug with Twitter API in stocks/ba/sentiment

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#5306]
There's an error with Twitter API in stocks/ba/sentiment, see:

<img width="433" alt="Screenshot 2023-08-10 at 3 02 38 PM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/25267873/2f070a80-9b12-4473-a9e5-063f5d886429">

Also, the Twitter API key validation is not correct. It's returning "Defined, test failed" even though the user is in a basic plan and has set the valid one.

**Comment by deeleeramone** [comment]
The new Twitter API "basic plan", or "free" access does not allow for requesting and retrieving data, only posting Tweets. These functions should be deprecated because they are no longer supported by Twitter.

![Screenshot 2023-08-11 at 10 07 58 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/ca63993c-f19b-4ce7-9f24-64909adb9d0e)

**Comment by jmaslek** [comment]
i already did deprecate them :P

**Comment by jmaslek** [comment]
will be edited with release/3.2.1
