### ISSUE TITLE
`setuptools<65.5.0` dependency when building on arch

### ISSUE THREAD

**Issue by v3natio** [OpenBB-finance/OpenBBTerminal#5354]
Hi all, amazing job you've done here.
I'm trying to package the source into an arch linux MAKEPKG, that way, I can host it on the arch user repository for all to download.
I was wondering on why there was a build dependency on `setuptools<65.5.0`, this ultimately makes the package conflict with a lot of other python packages that are on the AUR.

**Comment by powru9-gobVok-nutguj** [comment]
[]()

**Comment by powru9-gobVok-nutguj** [comment]
[]()

**Comment by powru9-gobVok-nutguj** [comment]
- [ ] - ****

**Comment by powru9-gobVok-nutguj** [comment]
[]()

**Comment by piiq** [comment]
hey @hooregi 
this was done about a year ago when a setuptools update broke down the numpy builds and everything downstream. there was some debate online at that time that showed that the numpy would not transition to a later version of setuptools for a while, so a version pin was an obvious immediate solution. I don't know if the issue was resolved and if numpy supports a later version of setuptools. If you can check and test - that'd be nice.

**Comment by powru9-gobVok-nutguj** [comment]
[]()

**Comment by hooregi** [comment]
Hi, numpy does support a later version. But I'll have to check and build openbb to see how the dependencies are managed. Currently busy with work but will check it out once I'm free, cheers!
