### ISSUE TITLE
[FR] Ability to change the position of stored data and temp

### ISSUE THREAD

**Issue by artaasd95** [OpenBB-finance/OpenBBTerminal#5434]
I have installed the OpenBB terminal in a drive that is not the windows drive for controlling the storage. But, now I don't know where is the storage files, I want to know if they stored in the windows drive or inside the installed location.  documentation has not contained any information about this matter.
Also I want ability to change the temp files storage.
So:
1. I want to know where are the downloaded files and data are stored?
2. I want ability to change the temp storage.

**Comment by deeleeramone** [comment]
#1. Is supposed to a settable parameter, but there is currently a bug with it: #5323 

#2. We may not have any control over because Python packages, and many programs, all keep their cache/temp storage in the same place, at the root of the operating system's user account in folders with names beginning with `.`
