### ISSUE TITLE
openbb.stocks.ca.screener prints Invalid data from website

### ISSUE THREAD

**Issue by jasonstrimpel** [OpenBB-finance/OpenBBTerminal#5569]
**Describe the bug**
When calling `openbb.stocks.ca.screener(["AAPL","MSFT","GOOG","NFLX","META","AMZN","NVDA"])` OpenBB prints _Invalid data from website_

**To Reproduce**
When calling `openbb.stocks.ca.screener(["AAPL","MSFT","GOOG","NFLX","META","AMZN","NVDA"])`

**Screenshots**
If you are running the terminal using the conda version please
rerun the terminal with `python terminal.py --debug`, and then
recreate your issue. Then include a screenshot of the entire 
error printout.

**Desktop (please complete the following information):**

- OS: macOS Monterrey 12.7
- Python version: 3.9

**Additional context**
The error stems from the ownership module in the finvizfinance.screener import:

![Screen Shot 2023-10-16 at 15 06 06](https://github.com/OpenBB-finance/OpenBBTerminal/assets/908118/34840874-9615-45a8-b542-0299c3e453e9)

**Comment by deeleeramone** [comment]
@jasonstrimpel, this has been patched in the latest version:

https://github.com/OpenBB-finance/OpenBBTerminal/releases/tag/v3.2.3

![Screenshot 2023-10-17 at 8 15 26 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/5eab9191-471a-4dca-bbb9-f8852189455c)

Closing because resolved by #5500
