### ISSUE TITLE
[Bug] `/crypto/onchain/hr` Function is dead - Error getting hashrate: 403 Forbidden

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5637]
```console
/crypto/onchain/hr BTC
```

```console
Error getting hashrate: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

Error getting BTC price: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by fadilparves** [comment]
Hi @deeleeramone , can you elaborate on how you got this error or maybe share the steps on reproducing it? Thanks

**Comment by deeleeramone** [comment]
To reproduce, use the Terminal command:

```
/crypto/onchain/hr BTC
```

**Comment by fadilparves** [comment]
@deeleeramone are you using Glassdoor enterprise account? As I check their latest pricing and API is now only offered under Enterprise account, it could be the 403 is because the current api key you are using is not valid anymore

<img width="1057" alt="Screenshot 2023-11-02 at 10 20 32 PM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/8860950/1a3dae49-5fe1-41c7-9425-5755a9f47a9f">

**Comment by deeleeramone** [comment]
> @deeleeramone are you using Glassdoor enterprise account? As I check their latest pricing and API is now only offered under Enterprise account, it could be the 403 is because the current api key you are using is not valid anymore
> <img alt="Screenshot 2023-11-02 at 10 20 32 PM" width="1057" src="https://user-images.githubusercontent.com/8860950/280020072-1a3dae49-5fe1-41c7-9425-5755a9f47a9f.png">

This is the only function using this source, so it should probably either, be removed, or, mapped to a source that works without a prohibitive paywall.
