### ISSUE TITLE
[Bug] `/stocks/fa/metrics -t AAPL --source AlphaVantage`: Data returned has no labels.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5648]
Recreate with:

```console
/stocks/fa/metrics -t AAPL --source AlphaVantage
```

![Screenshot 2023-11-01 at 10 47 39 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/ff347128-5b6d-4a15-806e-ac7e21a231f6)

**Comment by EricLi-Dev** [comment]
Would like to be assigned this issue!

Looked through the bug and it seems like it's something to do with the ```headers``` parameter that's being passed to the ```print_rich_table()``` in https://github.com/OpenBB-finance/OpenBBTerminal/blob/65bc870be348d8967e4e267e1f64d7861d8e2f11/openbb_terminal/stocks/fundamental_analysis/av_view.py?plain=1#L70C1-L70C22

Putting a dummy variable (like "A") instead of an empty string leads to labels being printed properly:
<img width="608" alt="image" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/38477812/2965130f-552c-4cfc-a63b-57f5d3717615">
<img width="1468" alt="image" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/38477812/51ebc080-409e-4feb-b68e-1ec0557de88f">

For the PR, I'm thinking as a solution I can just add the symbol name for the headers string.
