### ISSUE TITLE
[Bug] No results for balance sheet with yfinance ticker symbol

### ISSUE THREAD

**Issue by bm2609** [OpenBB-finance/OpenBBTerminal#5884]
Hello,

I'm using v4.0.1 and I want to fetch balance sheet data with yfinance as provider. Price data works well with yfinance ticker symbols (in this case BRK-B), but fetching balance sheet data does not work (also cash and income do not work, but are not shown in the following screenshot):

![Screenshot](https://github.com/OpenBB-finance/OpenBBTerminal/assets/49444885/5efa6ba3-4844-4b36-b37f-9266011af633)

- OS: Windows 10
- Python version: 3.10

Before updating to version 4.0.1, I used version 3.0 and there everything worked fine when using yfinance ticker symbols for fetching price data, balance sheet, income statement and cash statement data.

Best

**Comment by jmaslek** [comment]
Thanks for pointing this one out!

This was fixed in a recent PR (we were incorrectly handling the "-"), so running from source will work, or the next minor release.

<img width="653" alt="Screenshot 2023-12-13 at 7 29 26 PM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/18151143/7ed6d353-bef0-40dc-a1dc-f50c20fb58ac">

**Comment by deeleeramone** [comment]
The nightly build will also have it, `pip install openbb-nightly`
