### ISSUE TITLE
[Bug] - Report .html couldn't be created.

### ISSUE THREAD

**Issue by duonghobo** [OpenBB-finance/OpenBBTerminal#5953]
**Describe the bug**
As shown in the picture, the reports function cannot generatet the HTML even thought the ipynb file is created

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

**Screenshots**
<img width="563" alt="CleanShot 2024-01-15 at 01 08 00@2x" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/28920028/47de711a-20b7-4440-9bcb-2ce4d387f2d2">
<img width="529" alt="CleanShot 2024-01-15 at 01 09 51@2x" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/28920028/6c3cc7ce-f12d-493d-9c10-312a00f3097f">

**Desktop (please complete the following information):**

- OS: MacOS Monterrey

**Additional context**

**Comment by EricLi-Dev** [comment]
I looked through the generated .ipynb and it looks like it's because of a problem with ```finviz.get_stock(ticker)```. 

In cell 10:  ```info = finviz.get_stock(ticker)``` returns an empty DF.
<img width="722" alt="image" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/38477812/db77ddb7-ce15-40b4-88b8-a3c20fade395">

The report fails on cell 13  where it's trying to access fields not available in the ```info``` DataFrame. 
<img width="961" alt="image" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/38477812/2cb2db07-fd33-4e78-899e-65316aeb4fa2">

This is a current issue raised in the finviz package: https://github.com/mariostoev/finviz/issues/205
Looks like there needs to be a new release from finviz for this to be fixed on OpenBB
