### ISSUE TITLE
[Bug ] Dockerfile failed build on openbb-econdb version check

### ISSUE THREAD

**Issue by hadoopjax** [OpenBB-finance/OpenBBTerminal#6340]
**Describe the bug**
I tried to build the Docker container referenced [here](https://docs.openbb.co/platform/installation#docker) and received this error during the build:

![Screenshot 2024-04-24 at 10 35 58 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/5373223/78a3cb7d-d717-4e87-84e2-a65698630eca)

**To Reproduce**
1. `git clone https://github.com/OpenBB-finance/OpenBBTerminal.git`
2. `cd OpenBBTerminal `
3. `docker build -f build/docker/api.dockerfile -t openbb-platform:latest .`

**Desktop (please complete the following information):**

- OS: Mac Ventura 13.5
- Docker: 4.29.0 (145265)

**Additional context**
n/a

**Comment by deeleeramone** [comment]
Hi there,

Thanks for the report. I believe you are running into this issue because the package in question was only merged to the develop branch a couple of days ago and was not bundled in the release version.

If you switch to the `main` branch, this should get around that until that package is actually published.

**Comment by hadoopjax** [comment]
worked, thanks!
