### ISSUE TITLE
Edgar Filings 13F/D/G search by CUSIP, CRD, CIK, and plain text with math function. [FR]

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#776]
**What's the problem of not having this feature?**
This tool would enable the user to quickly ascertain the levels at which Institutional Investors are involved, who the players are, and what the overall direction of liquidity is. 

**Describe the solution you would like**
EDGAR filings search filters by CUSIP, CRD, CIK, Ticker, Company Name, and plain text, which would be able to search all Form 13F/13F-HR forms and incorporate a math function to be able to show current quarter Institutional holdings, further filtering/sorting for Shares, Calls, and Puts. Ideally a table displays the results with the Identities and Holdings of Shares, Calls, and Puts for the searched CUSIP number.  CUSIP search results would likely yield the most results and the most useful information. 

**Describe alternatives you've considered**
Paid websites. 

**Additional information**
This feature would be unique to the Terminal as no free alternative currently exists.

**Comment by kimi00jason** [comment]
for stocks/load XXX/dd/sec

Concurring to this suggestion.

The current EDGER is very feature rich in terms of displaying SEC filing. It should be the best for OpenBB to pull data from EDGER instead of private company like MarketWatch.

Example:
https://www.sec.gov/cgi-bin/browse-edgar?CIK=tsla

The API is to replace CIK value.

I am new to this terminal, I will take a look to see if this is something that I can take on and help out. But as for all market data, there's nothing more important than SEC filing. I would suggest to refine this part of feature as priority.
